openapi: 3.0.3
info:
  title: Project Management Tools API
  description: API endpoints for managing tasks in the project management application.
  version: 1.0.0
  contact:
    email: hei.fenohasina@gmail.com
servers:
  - url: https://localhost:8080
tags:
  - name: Task Management
    description: Endpoints for managing tasks

paths:
  /tasks:
    get:
      tags:
        - Task Management
      summary: Get a list of all tasks
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              example: |
                [
                  {
                    "id": 1,
                    "taskName": "Task A",
                    "description": "Description of Task A",
                    "deadline": "2023-08-30T12:00:00Z"
                  }
                ]
    post:
      tags:
        - Task Management
      summary: Create a new task
      requestBody:
        description: Task data to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Created task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

  /tasks/{id}:
    get:
      tags:
        - Task Management
      summary: Get a task by ID
      parameters:
        - in: path
          name: id
          description: Task ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
    put:
      tags:
        - Task Management
      summary: Update an existing task
      parameters:
        - in: path
          name: id
          description: Task ID
          required: true
          schema:
            type: integer
      requestBody:
        description: Updated task data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Updated task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid request
    delete:
      tags:
        - Task Management
      summary: Delete a task by ID
      parameters:
        - in: path
          name: id
          description: Task ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Task deleted
        '404':
          description: Task not found

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        taskName:
          type: string
        description:
          type: string
        deadline:
          type: string
          format: date-time
