openapi: 3.0.3
info:
  title: Project Management Tools API
  description: API endpoints for managing users in the project management application.
  version: 1.0.0
  contact:
    email: hei.fenohasina@gmail.com
servers:
  - url: https://localhost:8080
tags:
  - name: User Management
    description: Endpoints for managing users

paths:
  /users:
    get:
      tags:
        - User Management
      summary: Get a list of all users
      responses:
        '200':
          description: List of users
          content:
            application/json:
              example: |
                [
                  {
                    "id": 1,
                    "userName": "john_doe",
                    "email": "john@example.com",
                    "password": "hashedPassword",
                    "createdAt": "2023-08-30T12:34:56Z"
                  }
                ]
    post:
      tags:
        - User Management
      summary: Create a new user
      requestBody:
        description: User data to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Created user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /users/{id}:
    get:
      tags:
        - User Management
      summary: Get a user by ID
      parameters:
        - in: path
          name: id
          description: User ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
    put:
      tags:
        - User Management
      summary: Update an existing user
      parameters:
        - in: path
          name: id
          description: User ID
          required: true
          schema:
            type: integer
      requestBody:
        description: Updated user data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Updated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid request
    delete:
      tags:
        - User Management
      summary: Delete a user by ID
      parameters:
        - in: path
          name: id
          description: User ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User deleted
        '404':
          description: User not found

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        userName:
          type: string
        email:
          type: string
        password:
          type: string
        createdAt:
          type: string
          format: date-time


